### PR TITLE
stamps for c2e3-c2e7

### PR DESCRIPTION
**Pull request by the-soul-keeper**
added time stamps for both platforms for campaign 2 episode 3

### CODE REVIEW

**Comment by jpgill86** [comment]
Hi @the-soul-keeper! I'm sorry to say that I just discovered that [CritRole.com's podcast listings](https://critrole.com/podcast/campaign-2-ep1-ep51-mighty-nein-podcast/) for C2E1-C2E19, which I originally recommended using [here](https://github.com/critrolesync/critrolesync.github.io/issues/1), and which it appears you used, are different from what most podcast players provide. They are missing the voice-overs inserted at the beginning, middle, and end.

[This Podbean listing](https://criticalrole.podbean.com/) has versions of the episodes that include these additions. We should use this list for these episodes.

I'm sorry I didn't notice this earlier!

**Comment by the-soul-keeper** [comment]
No worries! I'll try to get those changes up this weekend, and use that
source from here on out! Thanks for letting me know!

**Comment by jpgill86** [comment]
Hi @the-soul-keeper! Please take a look at [this post](https://github.com/critrolesync/critrolesync.github.io/issues/1#issuecomment-655285824) for new recommendations on how to collect timestamps.

**Comment by the-soul-keeper** [comment]
Got it! I'll keep using Chrome and start using the links provided in the CritRoleSync app :)

**Comment by jpgill86** [comment]
Hello again @the-soul-keeper!

I have good news, and possibly bad news.

[The Podbean listing](https://criticalrole.podbean.com/) I asked you to switch to, and which was being linked to from CritRoleSync, stopped working a couple days ago. This podcast feed was controlled by Geek & Sundry.

There is a [new podcast feed](http://critrole.nerdistind.libsynpro.com/) that I think is controlled by Nerdist, and it contains the same episodes as the defunct G&S feed (all of Campaign 1, and C2E1-C2E19).

There is one important difference, however. The voice-overs that were inserted at the beginning, middle, and end are missing from the new feed for C2E1-C2E19. As a matter of fact, it appears that this new feed is the uncredited source of the C2E1-C2E19 podcasts linked to from [CritRole.com's podcast listing](https://critrole.com/podcast/campaign-2-ep1-ep51-mighty-nein-podcast/).

So, the good news is that the work you did here on C2E3-C2E7 is once again valid. I just added your contributions to CritRoleSync.

I want to credit everybody who contributes. Would you like to be referred to by your GitHub username, or something else?

The potential bad news is that if you followed my recommendations from a few days ago and have made new progress on any of C2E3-C2E19 using the now-defunct G&S feed, those times will no longer be correct since the voice-overs are missing from the Nerdist feed. I'm very sorry if this is the case!

**Pull request closed without merging**
